// apps/demo-h5-app/src/App.tsx
import { useState } from "react";
import { protocolCtx } from "./utils/protocolBridge";

export default function IframeChannel() {
  const [count, setCount] = useState(0);
  const [state, setState] = useState<"成功" | "失败" | undefined>();
  // 父组件返回的消息
  const [resInfo, setResInfo] = useState("");
  // // 接受的消息
  // const [receiveMsg, setReceiveMsg] = useState('')
  // // 回复的消息
  // const [replyMsg, setReplyMsg] = useState('')

  function handleShowLoading() {
    console.log("handleShowLoading");
    protocolCtx.emit("showLoading", count)
      .then(data => {
        console.log("handleShowLoading res data :>> ", data);
        setState("成功");
        setCount(count + 1);
        setResInfo(`${data}`);
      })
      .catch(err => {
        console.log("err :>> ", err);
        setState("失败");
        setResInfo(`${err}`);
      });
  }

  function handleSelectDate() {
    console.log("handleSelectDate");
    protocolCtx.emit("selectDate")
      .then(data => {
        console.log("handleSelectDate res data :>> ", data);
        setState("成功");
        setResInfo(`${data}`);
      })
      .catch(err => {
        console.log("err :>> ", err);
        setState("失败");
        setResInfo(`${err}`);
      });
  }

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: "12px" }}>
      <div className="card">
        <div className="card_title">发送消息</div>
        <div className="card_body">
          <div>
            <div style={{ display: "flex", gap: "12px" }}>
              <button onClick={handleShowLoading}>
                点击给父组件发送showLoading事件count: {count}
              </button>
              <button onClick={handleSelectDate}>
                点击给父组件发送selectDate事件
              </button>
            </div>
            <p>发送状态: {state}</p>
            <p>父组件返回的消息为: {resInfo}</p>
          </div>
        </div>
      </div>
    </div>
  );
}

// apps/demo-base-app/src/App.vue
<template>
  <div class="body">
    <h1>postMessage 测试</h1>
    <div class="card">
      <div class="card_body">
        <div>
          <p>触发的事件: {{ eventName }}</p>
          <p>接受到的参数: {{ eventParams }}</p>
          <p>返回的值: {{ eventResData }}</p>
        </div>
      </div>
    </div>
    <iframe src="http://localhost:6173/" frameborder="0" class="my-iframe"
      @load="protocolCtx.onContainerLoaded"></iframe>
  </div>
</template>

<script setup lang="ts">
import { onMounted, onUnmounted, ref } from 'vue'
import { protocolCtx } from './utils/protocolBridge'

// 触发的事件
const eventName = ref('')
// 接受到的参数
const eventParams = ref('')
// 接受的消息
const eventResData = ref('')


onMounted(() => {
  protocolCtx.on('selectDate', (str, successCallback, errorCallback) => {
    eventName.value = 'selectDate'
    eventParams.value = str
    if (Math.random() > 0.5) {
      const res = `${str ?? ''}-${Math.random()}`
      eventResData.value = res
      successCallback(res)
    } else {
      errorCallback()
    }
  })

  protocolCtx.on('showLoading', (str, successCallback, errorCallback) => {
    eventName.value = 'showLoading'
    eventParams.value = str ?? ''
    if (Math.random() > 0.5) {
      eventResData.value = `${str ?? ''}-${Math.random()}`
      successCallback()
    } else {
      errorCallback()
    }
  })
})

onUnmounted(() => {
  protocolCtx.off()
})

function onClick() {
  // const newCount = count.value + 1
  // myIframeRef.value?.contentWindow?.postMessage(`ha ${count.value}`, '*')
  // const contentWindow = myIframeRef.value?.contentWindow
  // console.log('newCount :>> ', newCount);
  // if (contentWindow) {
  // handleSendMessage(contentWindow, `ha ${newCount}`).then(res => {
  //   count.value = newCount
  //   state.value = '成功'
  //   resInfo.value = res as string
  // }).catch(err => {
  //   state.value = '失败'
  //   console.log('vue err :>> ', err);
  //   resInfo.value = JSON.stringify(err, null, 2)
  // })
  // const channel = new MessageChannel();

  // const port1 = channel.port1;
  // port1.onmessage = function (event) {
  //   console.log('Received from iframe:', event.data);
  // };
  // contentWindow.postMessage({ type: '__init_port__' }, '*', [channel.port2])
  // }
}

</script>

<style scoped>
.body {
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.my-iframe {
  height: 500px;
  margin-top: 12px;
  margin-left: 24px;
}
</style>
